server:
  port: 9090
spring:
  application:
    name: admin-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/p2p_account?serverTimezone=GMT%2B8
    username: root
    password: root

